modLoader="kotlinforforge"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
  modId="${mod_id}"
  version="${mod_version}"
  displayName="${mod_name}"
  displayURL="https://github.com/ianiiaannn/OperationRelife"
  authors="${mod_authors}"
  description='''${mod_description}'''
[[dependencies.${mod_id}]]
  modId="kotlinforforge"
  mandatory=true
  versionRange="${kff_version}"
  ordering="NONE"
  side="BOTH"
[[dependencies.${mod_id}]]
  modId="forge"
  mandatory=true
  versionRange="${neo_version_range}"
  ordering="NONE"
  side="BOTH"
[[dependencies.${mod_id}]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"
