modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]]
modId="operation_relife"
version="${file.jarVersion}"
displayName="Operation Relife"
authors="ianiiaannn(Coding), TWDragonflyTommy(Modeling)"
description='''What is behind the dragon?'''
[[dependencies.operationrelife]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.operationrelife]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3)"
    ordering="NONE"
    side="BOTH"
